vim.api.nvim_create_user_command('StacheOpenTask', function()
    require 'stache'.open_item()
end, {})
vim.api.nvim_create_user_command('StacheRunAll', function(_)
    require 'stache'.buf_exec_all_blocks(0)
end, {})
